# Generated by Django 5.0.6 on 2026-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store", models.CharField(max_length=120, verbose_name="Tienda")),
                (
                    "requester",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Comercial"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motivo")),
                ("items", models.JSONField(default=list, verbose_name="Materiales")),
                (
                    "forwarded",
                    models.BooleanField(
                        default=False, verbose_name="Reenviado al webhook"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
            ],
            options={
                "verbose_name": "Solicitud de material",
                "verbose_name_plural": "Solicitudes de material",
                "ordering": ["-created_at"],
            },
        ),
    ]
