# Generated by Django 5.0.6 on 2026-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Identificador interno que se envía al webhook (ej. peanas).",
                        max_length=60,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "units_spec",
                    models.CharField(
                        help_text="Números, comas y/o rangos. Ej: 1000  ·  1,2,3,4,5  ·  1-30",
                        max_length=200,
                        verbose_name="Unidades",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiales",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("active", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Tienda",
                "verbose_name_plural": "Tiendas",
                "ordering": ["order", "name"],
            },
        ),
    ]
